# Generated by Django 2.0 on 2018-09-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schooldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('elect_eur', models.FloatField()),
                ('elect_kwh', models.FloatField()),
                ('heating_eur', models.FloatField()),
                ('heating_kwh', models.FloatField()),
                ('water_eur', models.FloatField()),
                ('water_litres', models.FloatField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
